package com.hhldiniz.praondefoiomeudinheiro.data.local.entity

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class CategoryEntityTest {

    @Test
    fun defaultCategories_hasExpectedSize() {
        assertEquals(10, defaultCategories().size)
    }

    @Test
    fun defaultCategories_haveExpectedNamesInOrder() {
        val names = defaultCategories().map { it.name }
        assertEquals(
            listOf(
                "Alimentacao",
                "Transporte",
                "Lazer",
                "Saude",
                "Educacao",
                "Moradia",
                "Salario",
                "Freelance",
                "Investimentos",
                "Outros"
            ),
            names
        )
    }

    @Test
    fun defaultCategories_haveAutoGeneratedIds() {
        defaultCategories().forEach { category ->
            assertEquals(0, category.id)
        }
    }

    @Test
    fun categoryStoresName() {
        val category = Category(name = "Teste")
        assertEquals("Teste", category.name)
    }

    @Test
    fun defaultCategories_uniqueNames() {
        val names = defaultCategories().map { it.name }
        assertEquals(names.toSet().size, names.size)
    }
}
